### ISSUE TITLE
Question: Inject Multiline Secrets into Container

### ISSUE THREAD

**Issue by LMSSonos** [Azure/acr#348]
Hello

I created a task using the yaml file and define a (multiline) secret.  

```
version: v1.1.0
secrets:
 - id: mysecret
   keyvault: https://mykeyvault.vault.azure.net/secrets/mysecret/1235678
steps:  
 - cmd: myacr.azurecr.io/testcontainer:latest
```

How can I access the secret within my container (testcontainer:latest)? I was hoping to get the secret as a file in the /run/secrets folder or something similar. 

I can output the secret as follows
```
 - cmd: >
    bash echo '{{.Secrets.mysecret}}'
```

But I did not find out how to bass it into my docker container that is run.

Thanks for any help

**Comment by northtyphoon** [comment]
@LMSSonos  for now, can you pass the secrets as env? 

```
version: v1.1.0
secrets:
 - id: mysecret
   keyvault: https://mykeyvault.vault.azure.net/secrets/mysecret/1235678
steps:
 - cmd: myacr.azurecr.io/testcontainer:latest
   env: 
    - "mysecret1={{.Secrets.mysecret1}}"
    - "mysecret2={{.Secrets.mysecret2}}"
```

Your script in the container can read the env and dump to /run/secrets. 

If the secret value has mulitple lines, you also need to pass the encoded value in env and your script can decode it. The following is an example 

```
 - cmd: bash -c 'echo $mysecret1 | base64 -d >> secrets && echo "" >> secrets && echo $mysecret2 | base64 -d >> secrets && cat secrets'
   env: 
    - "mysecret1={{.Secrets.mysecret1 | b64enc}}"
    - "mysecret2={{.Secrets.mysecret2 | b64enc}}"
```
