### ISSUE TITLE
Buildx cache export feature is currently not supported for docker driver

### ISSUE THREAD

**Issue by michailbrynard** [Azure/acr#351]
**Describe the bug**
The acr/docs/tasks/buildx/build_with_cache.yaml task fails with
> Error: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")

**To Reproduce**
1. Follow the steps in https://github.com/Azure/acr/tree/master/docs/tasks/buildx#build-with-cache

**Expected behavior**
Docker image should be built and the result cached to to the image specified.

**Comment by northtyphoon** [comment]
@shahidkhuram can you provide an example using `--cache: "enabled"` in `build` step?

/cc: @SteveLasker

**Comment by shahzzzam** [comment]
Hi @michailbrynard, Can you try using build_with_cache_2.yaml instead of build_with_cache.yaml and see if it works?

Thank you

**Comment by michailbrynard** [comment]
That works, thank you. We'll use the `--cache: "enabled"` option, wasn't aware of it before.

**Comment by MatthiasWinzeler** [comment]
Hi @shahzzzam - thanks for the hint with `cache: enabled`!

While implementing this in our pipelines we found out that the [bootstrap step](https://github.com/Azure/acr/tree/main/docs/tasks/buildx#run-buildx-in-acr-tasks) which publishes the `buildx` image to the registry seems to not be needed anymore when using `cache: enabled`. Maybe you want to mention all this in the docs :)

For anyone out there looking how to actually put this together to tag & push an image with caching, here a more complete example:

build.yaml:
```
version: v1.1.0
stepTimeout: 1200 # quickly needed for some larger image builds; default is 10mins
steps:
- build: -t $Registry/{{.Values.REPOSITORY_NAME}}:{{.Values.TAG_NAME}} -f {{.Values.DOCKERFILE}} .
  cache: enabled
- push:
  - $Registry/{{.Values.REPOSITORY_NAME}}:{{.Values.TAG_NAME}}
```

which is invoked as follows:

```
az acr run -f acr_build.yml -r <registry-name> \
  --set REPOSITORY_NAME=<registry-name> \
  --set TAG_NAME=latest \
  --set DOCKERFILE=Dockerfile \ 
  .
```

**Comment by MatthiasWinzeler** [comment]
After running these builds for a while, we noticed that exporting the docker image took a lot of time, even if cached; we filed a support request with microsoft and got the following instructions, which fixes the issue. 

The current way to use caches is:

acr_build.yml
```yaml
version: v1.1.0
stepTimeout: 3600
steps:
- cmd: buildx create --use # start buildkit
- cmd: buildx build -t $$Registry/{{.Values.REPOSITORY_NAME}}:{{.Values.TAG_NAME}} -f {{.Values.DOCKERFILE}} --push --cache-to=type=registry,ref=$$Registry/{{.Values.REPOSITORY_NAME}}:cache,mode=max --cache-from=type=registry,ref=$$Registry/{{.Values.REPOSITORY_NAME}}:cache .
```

invocation:
```
az acr run -f acr_build.yml -r <registry-name> \
  --set REPOSITORY_NAME=<image-name> \
  --set TAG_NAME=latest \
  --set DOCKERFILE=Dockerfile \ 
  .
```
