### ISSUE TITLE
TLS error when pulling image from ACR through Private Link

### ISSUE THREAD

**Issue by r3-jerrysteele** [Azure/acr#425]
**Describe the bug**
TLS error when pulling image from ACR through Private Link

**To Reproduce**
1. Create ACR (Premium SKU, Georeplication enabled)
2. Set up Private Link, Private Endpoint and Private DNS as per the [official article](https://docs.microsoft.com/en-gb/azure/container-registry/container-registry-private-link)
3. Write a simple pod manifest to pull from the created registry via the Private Link:

```
apiVersion: v1
kind: Pod
metadata:
  name: private-reg-ubuntu
spec:
  containers:
  - name: private-reg-ubuntu-container
    image: myregistry.privatelink.azurecr.io/ubuntu-test:mytag
```

**Expected behavior**
The image is pulled to my AKS cluster via the private link. What actually happens is I get a TLS error:

```
Failed to pull image "myregistry.privatelink.azurecr.io/ubuntu-test:mytag": rpc error: code = Unknown desc = Error response from daemon: Get https://r3safeacrtest.privatelink.azurecr.io/v2/: x509: certificate is valid for *.azurecr.io, not r3safeacrtest.privatelink.azurecr.io
```

So it appears to be reaching the registry via the private link, but the TLS certificate for the registry itself does not support the DNS name given to the registry (which was specified in the article as `<registry_name>.privatelink.azurecr.io`)

**Any relevant environment information**
 - Environment where this is happening is AKS.
 - Setup is via Terraform, but I have confirmed that all resources are created as per the "CLI setup" part of the article

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.
