### ISSUE TITLE
ACR Task Push Step to support retagging

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#481]
**What is the problem you're trying to solve**
Minimizing the number of steps required, while reducing the time to execute

**Describe the solution you'd like**
In some scenarios, an image is pulled with a specific registry and/or tag. The image should be pushed to the current registry.
To achieve this I must write separate steps for pull, tag, tag, tag, push [collection]
The ask is to incorporate retagging with the push.
And/or, add an import step:
```yaml
  - id: retag-base-image
    when: ['pull-base-image']
    cmd: docker tag {{.Values.REGISTRY_FROM_URL}}node:15-alpine {{.Run.Registry}}/node:15-alpine
  - id: retag-base-image-unique-tag
    when: ['pull-base-image']
    cmd: docker tag {{.Values.REGISTRY_FROM_URL}}node:15-alpine {{.Run.Registry}}/node:15-alpine-{{.Run.ID}}
  - id: push-base-image
    when: ['retag-base-image', 'retag-base-image-unique-tag']
    push: 
    - "{{.Run.Registry}}/node:15-alpine"
    - "{{.Run.Registry}}/node:15-alpine-{{.Run.ID}}"
```
Could become:
```yaml
  - id: push-with-retag
    when: ['retag-base-image', 'retag-base-image-unique-tag']
    push: 
    - {{.Values.REGISTRY_FROM_URL}}node:15-alpine, "{{.Run.Registry}}/node:15-alpine"
    - {{.Values.REGISTRY_FROM_URL}}node:15-alpine, "{{.Run.Registry}}/node:15-alpine-{{.Run.ID}}"
```
or
```yaml
  - id: import
    import: >
      --source={{.Values.REGISTRY_FROM_URL}}node:15-alpine
      --target={{.Run.Registry}}/node:15-alpine
      --target={{.Run.Registry}}/node:15-alpine-{{.Run.ID}}
```
**Additional context**
