### ISSUE TITLE
ACR Env variables -syntax and having trouble setting them in cmd of an ACR YAML file

### ISSUE THREAD

**Issue by philip-young** [Azure/acr#649]
I am trying to set environment variables for a 'cmd' task that I am running from an ACR YAML I have created and am using an ACR task to run, but the environment variables are not making it through to the .NET 6 application I am running in the container. I have had a lot of trouble finding the right way to do this in the documentation.. does this look right? I have tried a few other ways and they don't get accepted when I try to run the Task (it complains about the YAML being incorrect)

- cmd: $Registry/myimage:latest --env ["mySetting1=myValue1", "mySetting2=myValue2"]

All I am looking to do is set the Environment config variables for the .NET Application I am running after the build and push is completed in the YAML.
Sample YAML File I am using:
```
version: v1.1.0
steps:
    - build: -t $Registry/myimage -f Dockerfile .
    - push: 
        - $Registry/myimage:latest
    - cmd: $Registry/myimage:latest --env ["mySetting1=myValue1", "mySetting2=myValue2"]

```

**To Reproduce**
1. Create YAML File.
2. Create ACR Task to run based on the file.
3. When the -cmd portion of the YAML runs, the container runs but has the variables it needs. 

**Expected behavior**
The environment variables that I am setting are present in the container run.
