### ISSUE TITLE
Allow `buildkit` build in `az acr build`

### ISSUE THREAD

**Issue by HappyRashair** [Azure/acr#721]
**What is the problem you're trying to solve**
I'd like to use new `BuildKit` features in my Dockerfile.

**Describe the solution you'd like**
It would be nice to have an argument to use `BuildKit` build in acr build task, e.g. `--buildkit`

**Additional context**
Related issue: https://github.com/apache/airflow/issues/27690

**Comment by jeevankuduvaravindran** [comment]
Is there any updates on this feature? we need buildkit to be working on acr for one of our publish functionalities.

**Comment by HappyRashair** [comment]
Is it very hard to implement this?

**Comment by masonhuemmer** [comment]
Any update on this?

**Comment by manas007** [comment]
why is there no update on this for a year ?

**Comment by terencet-dev** [comment]
Apologies for the delay, our team is looking into this

**Comment by Matthew0x** [comment]
I believe you can only do it using the ACR task template, as a wrapper for the "docker build" command, which runs in a "build" step on the ACR agent.

```
version: v1.1.0
steps:
  - id: <task-name>
    build: --tag $Registry/<image-name>:$ID --file <path-to-dockerfile> .  --build-arg SOMETHING={{.Values.SOMETHING}}
    when: ["-"]
    env: 
      - DOCKER_BUILDKIT=1
```

It appears to be working for me in a similar use-case.

**Comment by sharmuz** [comment]
@terencet-dev Sorry to nudge again, but is there any word on buildkit being supported?

Not being able to use mounts (esp. for secret/ssh) is proving to be a major feature gap in acr.

**Comment by doanduyhai** [comment]
So by combining some answers here and from StackOverflow

**`acr-build-file.yml`**

```yaml
version: v1.1.0
steps:
  - build: -t $Registry/{{.Values.image}} --file <path_to_your_Dockerfile> .
    env:
      - DOCKER_BUILDKIT=1
  - push:
      - "$Registry/{{.Values.image}}"
```

Command to use
```shell
cd <source_folder>
az acr run \
 -f ./acr-build-task.yml \
 --registry <acr_name> \
 --set image="<image_name>:<image_tag>" .
```

It worked for me
