### ISSUE TITLE
ACR task command fails with unmarshall error

### ISSUE THREAD

**Issue by praveenpeejay** [Azure/acr#840]
I have created a ACR task with following bicep

```yml
resource cr_purge_image_task 'Microsoft.ContainerRegistry/registries/tasks@2019-06-01-preview' = {
  parent: cr_res
  name: 'purge_image'
  location: resourceGroup().location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    credentials: {
      customRegistries: {
        '${crName}.azurecr.io': {
          identity: '[system]'
        }
      }
    }
    platform: {
      os: 'linux'
      architecture: 'amd64'
    }
    step: {
      type: 'EncodedTask'
      //encodedTaskContent: base64('acr purge --filter "imagename:.*" --ago 1d --untagged --dry-run') gives same error
      // converted following cmd to base64 string acr purge --filter 'imagename:.*' --ago 1d --untagged --dry-run
      encodedTaskContent: 'YWNyIHB1cmdlIC0tZmlsdGVyICdpbWFnZW5hbWU6LionIC0tYWdvIDFkIC0tdW50YWdnZWQgLS1kcnktcnVu'
    }
  }
}
```

In the DevOps pipeline yml to run the ACR task

```yml
- task: AzureCLI@2
                  inputs:
                    azureSubscription: 'ACE-ALZ-AzureDevOps-ServiceConnection-Sub-f2959b76-4f0c-4064-ba70-1f3f1d61baf2'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                        az acr task run -n purge_image -r registryname
```

gives following error

```log
failed to unmarshal task before running: failed to deserialize task and validate: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `acr pur...` into graph.Task


Run ID: db18 failed after 1s. Error: failed during run, err: exit status 1

ERROR: Run failed
```

Is the base64 format wrong that is used while creating task?
